version: 0.2

phases:
  install:
    commands:
      - pyenv install -s 3.10.0
      - pyenv global 3.10.0
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - cd front-end-react
      - npm install
      - npm run build
      - aws s3 sync build s3://jwdr1234-trivia-app-bucket/
